# Generated by Django 2.0.1 on 2018-03-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180309_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.IntegerField(default=1),
        ),
    ]
