# Generated by Django 2.0.1 on 2018-03-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
